PhotoProspector/ViewModels/DeleteUserViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Mail;
using PhotoProspector.Validations;

namespace PhotoProspector.ViewModels
{
    public class DeleteUserViewModel
    {
        public DeleteUserViewModel() : this(DeleteUserStatus.Initial, "") { }

        public DeleteUserViewModel(DeleteUserStatus status = DeleteUserStatus.Initial, string errorMessage = "")
        {
            Status = status;
            ErrorMessage = errorMessage;
        }

        public string alias { get; set; }

        [Required]
        [EmailWithDomain("microsoft.com")]
        [DisplayName("Email")]
        public string MSEmail
        {
            get
            {
                return alias + "@microsoft.com";
            }
            set
            {
                try
                {
                    var mail = new MailAddress(value);
                    alias = mail.User;
                }
                catch
                {
                    alias = "";
                }
            }
        }

        [Required]
        [DefaultValue("")]
        [InvidationCodeMatchEmail]
        [DisplayName("Code")]
        public string SignUpCode { get; set; }

        public DeleteUserStatus Status { get; private set; }

        public string ErrorMessage { get; private set; }

        public enum DeleteUserStatus
        {
            Initial = 1,
            DeleteUserSucceed = 2,
            DeleteUserFailed = 3
        }
    }
}

PhotoProspector/ViewModels/SignUpViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Mail;
using System.Web;
using PhotoProspector.Models;
using PhotoProspector.Validations;

namespace PhotoProspector.ViewModels
{
    public class SignUpViewModel : Person
    {
        [Required]
        public new HttpPostedFileBase photoPath { get; set; }

        [Required]
        [EmailWithDomain("microsoft.com")]
        [DisplayName("Email")]
        public string MSEmail
        {
            get
            {
                return alias + "@microsoft.com";
            }
            set
            {
                try
                {
                    var mail = new MailAddress(value);
                    alias = mail.User;
                }
                catch
                {
                    alias = "";
                }
            }
        }

        public SignUpViewModel() : this(SignUpStatus.Initial, "") { }

        public SignUpViewModel(SignUpStatus status = SignUpStatus.Initial, string errorMessage = "")
        {
            Status = status;
            ErrorMessage = errorMessage;
            base.photoPath = title = specialty = team = favoritesport = "";
        }

        [DefaultValue("")]
        [Required]
        [InvidationCodeMatchEmail]
        [DisplayName("Code")]
        public string SignUpCode { get; set; }

        public SignUpStatus Status { get; private set; }

        public string ErrorMessage { get; private set; }

        public enum SignUpStatus
        {
            Initial = 1,
            SignUpSucceed = 2,
            SignUpFailed = 3
        }
    }
}

PhotoProspector/Controllers/SignUpController.cs
using System.IO;
using System.Web.Mvc;
using PhotoProspector.Services;
using PhotoProspector.ViewModels;

namespace PhotoProspector.Controllers
{
    public class SignUpController : Controller
    {
        private readonly IImageService imageService;
        private readonly IFileService fileService;
        private readonly IUserService userService;
        private readonly IMessageService messageService;
        private readonly ITrainingService trainingService;

        public SignUpController(
            IImageService imageService,
            IFileService fileService,
            IUserService userService,
            IMessageService messageService,
            ITrainingService trainingService)
        {
            this.imageService = imageService;
            this.fileService = fileService;
            this.userService = userService;
            this.messageService = messageService;
            this.trainingService = trainingService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new SignUpViewModel());
        }

        public ActionResult Index(SignUpViewModel signUpViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var filename = Path.GetFileName(signUpViewModel.photoPath.FileName);
                    var tempFolder = Server.MapPath("~/TempImg/");
                    if (!Directory.Exists(tempFolder))
                    {
                        Directory.CreateDirectory(tempFolder);
                    }
                    var savedFullPaht = tempFolder + fileService.filenameHashed(filename);
                    signUpViewModel.photoPath.SaveAs(savedFullPaht);
                    if (userService.InsertUserToSQL(savedFullPaht, signUpViewModel, Server.MapPath("~/ImageSource/")))
                    {
                        string trainpath = Server.MapPath("~/ImageSource/");
                        trainingService.StartTraining(trainpath);
                        return View(new SignUpViewModel(SignUpViewModel.SignUpStatus.SignUpSucceed));
                    }
                    else
                    {
                        return View(new SignUpViewModel(SignUpViewModel.SignUpStatus.SignUpFailed, "Sign up failed. Please try again later."));
                    }
                }
            }
            catch
            {
                return View(new SignUpViewModel(SignUpViewModel.SignUpStatus.SignUpFailed, "Sign up failed. Please try again later."));
            }

            return View(signUpViewModel);
        }

        [HttpGet]
        public ActionResult DeleteUser()
        {
            return View(new DeleteUserViewModel());
        }

        [HttpPost]
        public ActionResult DeleteUser(DeleteUserViewModel deleteUserViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (userService.DeleteUserFromSQL(deleteUserViewModel.alias, Server.MapPath("~/ImageSource/")))
                    {
                        return View(new DeleteUserViewModel(DeleteUserViewModel.DeleteUserStatus.DeleteUserSucceed));
                    }
                    else
                    {
                        return View(new DeleteUserViewModel(DeleteUserViewModel.DeleteUserStatus.DeleteUserFailed, "Delete user failed. User email doesn't exist."));
                    }
                }
            }
            catch
            {
                return View(new DeleteUserViewModel(DeleteUserViewModel.DeleteUserStatus.DeleteUserFailed, "Delete user failed. Please try again later."));
            }

            return View(deleteUserViewModel);
        }

        [HttpPost]
        public ActionResult SendInvitationCode(string email)
        {
            try
            {
                messageService.SendInvitationCode(email);
            }
            catch
            {
                return Json(new { success = false, errorMessage = "Send invitation code failed, please try later." });
            }
            return Json(new { success = true });
        }
    }
}

PhotoProspector/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PhotoProspector.Services;

namespace PhotoProspector.Controllers
{
    public class UploadController : Controller
    {
        private const int UploadScreenWidth = 800;  // Change the value of the width of the image on the screen

        private const string UploadImgFolder = "/images";
        private const string UploadPath = "~" + UploadImgFolder;

        private readonly IImageService imageService;
        private readonly IFileService fileService;

        public UploadController(
            IImageService imageService,
            IFileService fileService)
        {
            this.imageService = imageService;
            this.fileService = fileService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null || !files.Any())
            {
                return Json(new { success = false, errorMessage = "No file uploaded." });
            }
            var file = files.FirstOrDefault();  // get ONE only
            if (file == null || !fileService.IsImage(file))
            {
                return Json(new { success = false, errorMessage = "File is of wrong format. Only image with .jpg, .jpeg or .png files is supported." });
            }
            if (file.ContentLength <= 0)
            {
                return Json(new { success = false, errorMessage = "File cannot be empty." });
            }
            var webPath = GetTempSavedFilePath(file);
            return Json(new { success = true, fileName = webPath.Replace("/", "\\") }); // success
        }

        [HttpPost]
        public ActionResult Save(string fileName)
        {
            try
            {
                // Get file from temporary folder
                var fn = Path.Combine(Server.MapPath(UploadPath), Path.GetFileName(fileName));
                var img = new WebImage(fn);
                // ... delete the temporary file,...
                System.IO.File.Delete(fn);
                // ... and save the new one.
                var newFileName = Path.Combine(UploadPath, Path.GetFileName(fn));
                var newFileLocation = Server.MapPath(newFileName);
                if (Directory.Exists(Path.GetDirectoryName(newFileLocation)) == false)
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(newFileLocation));
                }

                img.Save(newFileLocation);

                int w = 800;
                int h = 800;

                string filename = Path.GetFileName(fn);

                string[] arrays = filename.Split('.');
                string cutfilename = arrays[0] + "cut." + arrays[arrays.Length - 1];
                string cutfilepath = Server.MapPath("~/images/") + cutfilename;

                this.imageService.CutImg(newFileLocation, cutfilepath, w, h, "HW");

                if (System.IO.File.Exists(newFileLocation))
                {
                    System.IO.File.Delete(newFileLocation);
                }


                return Json(new { success = true, uploadFileLocation = "." + Path.Combine(UploadImgFolder, cutfilename) });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = "Unable to upload file.\nERRORINFO: " + ex.Message });
            }
        }

        private string GetTempSavedFilePath(HttpPostedFileBase file)
        {
            // Define destination
            var serverPath = Server.MapPath(UploadPath);
            if (Directory.Exists(serverPath) == false)
            {
                Directory.CreateDirectory(serverPath);
            }

            // Generate unique file name
            var fileName = Path.GetFileName(file.FileName);
            fileName = SaveTemporaryUploadFileImage(file, serverPath, fileName);

            // Clean up old files after every save
            CleanUpTempFolder(1);
            return Path.Combine(UploadPath, fileName);
        }

        private static string SaveTemporaryUploadFileImage(HttpPostedFileBase file, string serverPath, string fileName)
        {
            var img = new WebImage(file.InputStream);
            var ratio = img.Height / (double)img.Width;
            img.Resize(UploadScreenWidth, (int)(UploadScreenWidth * ratio));

            var fullFileName = Path.Combine(serverPath, fileName);
            if (System.IO.File.Exists(fullFileName))
            {
                System.IO.File.Delete(fullFileName);
            }

            img.Save(fullFileName);
            return Path.GetFileName(img.FileName);
        }

        private void CleanUpTempFolder(int hoursOld)
        {
            try
            {
                var currentUtcNow = DateTime.UtcNow;
                var serverPath = Server.MapPath("~/Temp");
                if (!Directory.Exists(serverPath)) return;
                var fileEntries = Directory.GetFiles(serverPath);
                foreach (var fileEntry in fileEntries)
                {
                    var fileCreationTime = System.IO.File.GetCreationTimeUtc(fileEntry);
                    var res = currentUtcNow - fileCreationTime;
                    if (res.TotalHours > hoursOld)
                    {
                        System.IO.File.Delete(fileEntry);
                    }
                }
            }
            catch
            {
                // Deliberately empty.
            }
        }
    }
}

PhotoProspector/Views/SignUp/DeleteUser.cshtml
@model PhotoProspector.ViewModels.DeleteUserViewModel

@{
    ViewBag.Title = "DeleteUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/deleteuser")
@Styles.Render("~/Content/profile")

<div class="user_container">
    <h1 id="delete_title">Delete Profile</h1>

    <div>
        @{if (Model.Status == PhotoProspector.ViewModels.DeleteUserViewModel.DeleteUserStatus.DeleteUserSucceed)
            {
                <p class="user_message success_message">Delete successfully, click @Html.ActionLink("here", "Index", "Upload") back.</p>
            }
            else if (Model.Status == PhotoProspector.ViewModels.DeleteUserViewModel.DeleteUserStatus.DeleteUserFailed)
            {
                <p class="user_message failure_message">@Model.ErrorMessage</p>
            }
        }
    </div>

    <div id="delete_form_container">
        @using (Html.BeginForm("DeleteUser", "SignUp", FormMethod.Post, new { id = "sign_up_form", enctype = "multipart/form-data" }))
            {
            @Html.ValidationSummary(true)
            <fieldset>
                <legend><span class="number delete_legend">1</span>Basic Info*</legend>
                @Html.LabelFor(model => model.MSEmail)
                @Html.EditorFor(model => model.MSEmail)
                <button id="forget_invitation_code_button" class="get_code_btn delete_page_btn" type="button">Forget Code</button>

                @Html.LabelFor(model => model.SignUpCode)
                @Html.EditorFor(model => model.SignUpCode)

                @Html.ValidationMessageFor(model => model.SignUpCode)
            </fieldset>
            <button type="submit" id="delete_buton" class="delete">Delete</button>
            @Html.ActionLink("I want to sign up profile.", "Index", "SignUp")
        }
    </div>
</div>

PhotoProspector/Views/SignUp/Index.cshtml
@model PhotoProspector.ViewModels.SignUpViewModel
@{
    ViewBag.Title = "Sign Up";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/signup")
@Styles.Render("~/Content/profile")

<div class="user_container">
    <h1 id="signup_title">Sign You Up!</h1>

    <div>
        @{if (Model.Status == PhotoProspector.ViewModels.SignUpViewModel.SignUpStatus.SignUpSucceed)
            {
                <p class="user_message success_message">Congratulation! You've signed up, click @Html.ActionLink("here", "Index", "Upload") back.</p>
            }
            else if (Model.Status == PhotoProspector.ViewModels.SignUpViewModel.SignUpStatus.SignUpFailed)
            {
                <p class="user_message failure_message">@Model.ErrorMessage</p>
            }
        }
    </div>

    <div id="signup_form_container">
        @using (Html.BeginForm("Index", "SignUp", FormMethod.Post, new { id = "sign_up_form", enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true)
            <fieldset>
                <legend><span class="number signup_legend">1</span>Your Basic Info*</legend>
                @Html.LabelFor(model => model.MSEmail)
                @Html.EditorFor(model => model.MSEmail)
                <button id="get_invitation_code_button" class="get_code_btn sign_up_page_btn" type="button">Get Code</button>

                @Html.LabelFor(model => model.displayname)
                @Html.EditorFor(model => model.displayname)

                @Html.LabelFor(model => model.photoPath)
                <div id="avatar_upload_editor">
                    <img id="avatar_preview_img" src="~/Content/Images/avatar.png" />
                    @Html.EditorFor(model => model.photoPath)
                </div>
            </fieldset>

            <fieldset>
                <legend><span class="number signup_legend">2</span>Your Profile (Optional)</legend>
                @Html.LabelFor(model => model.title)
                @Html.EditorFor(model => model.title)

                @Html.LabelFor(model => model.specialty)
                @Html.EditorFor(model => model.specialty)

                @Html.LabelFor(model => model.team)
                @Html.EditorFor(model => model.team)

                @Html.LabelFor(model => model.favoritesport)
                @Html.EditorFor(model => model.favoritesport)
            </fieldset>

            <fieldset>
                <legend><span class="number signup_legend">3</span>Invitation*</legend>
                @Html.LabelFor(model => model.SignUpCode)
                @Html.EditorFor(model => model.SignUpCode)

                @Html.ValidationMessageFor(model => model.SignUpCode)

                <p id="invitation_code_note">*Invitation Code is used for signing up for qualified user. Please use your <b>Microsoft email account</b> to retrieve.</p>
            </fieldset>

            @Html.HiddenFor(model => model.IsCustomer);

            <button type="submit" id="signup_buton" class="signup">Sign Up</button>
            @Html.ActionLink("I want to delete my existing profile.", "DeleteUser", "SignUp")
        }
    </div>
</div>