PhotoProspector/Controllers/ScanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using PhotoProspector.Helpers;
using PhotoProspector.Models;
using PhotoProspector.Services;
using PhotoProspector.ViewModels;

namespace PhotoProspector.Controllers
{
    public class ScanController : Controller
    {
        private static double progress = 0.00f;

        private readonly IUserService userService;
        private readonly IImageService imageService;
        private readonly IScanningService scanningService;
        private readonly ITrainingService trainingService;

        public ScanController(
            IUserService userService,
            IImageService imageService,
            IScanningService scanningService,
            ITrainingService trainingService)
        {
            this.userService = userService;
            this.imageService = imageService;
            this.scanningService = scanningService;
            this.trainingService = trainingService;
        }

        [HttpPost]
        public ActionResult Index(string fileName)
        {
            ViewBag.fileName = fileName;
            return View();
        }

        [HttpPost]
        public ActionResult Scan(string filePath)
        {
            progress = 0.00f;

            PersonListViewModel personlist = new PersonListViewModel();

#if DEBUG
            personlist = fakeViewModel();
            progress = 100;
            return PartialView(personlist);
#endif

            string trainingpath = Server.MapPath("~/ImageSource/");
            //string trainingpath = "C:\\ASPNET\\FaceWebSite\\ImageSource\\";
            string[] array = filePath.Split('\\');
            string filename = array[array.Length - 1];
            string filepath = Server.MapPath("~/images/") + filename;

            string[] arrays2 = filename.Split('.');
            string drawfilename = arrays2[0] + "draw." + arrays2[1];
            string drawfilepath = Server.MapPath("~/images/") + drawfilename;

            progress = 10f;

            int top = 0;
            int left = 0;
            int width = 0;
            int height = 0;

            FileStream fs = new FileStream(filepath, FileMode.Open, FileAccess.ReadWrite);
            byte[] imdata = new byte[fs.Length];
            fs.Read(imdata, 0, (int)fs.Length);
            fs.Close();

            progress = 25f;

            string result = trainingService.SyncRequest(imdata);

            progress = 40f;

            if (result == "[]")
            {
                string[] noname = { "No face Detected!" };
                int[] noface = { 0, 0, 0, 0 };

                imageService.DrawImg(filepath, drawfilepath, noface, noname, 1);

                personlist.ImageURL = "./images/" + drawfilename;
            }
            else
            {
                string[] substr = result.StringSplit("},{");
                string res = "";
                int facenum = substr.Length;
                int[] intarray = new int[4 * facenum];
                string[] alias = new string[substr.Length];
                string faceid = "";

                for (int i = 0; i < substr.Length; i++)
                {

                    res = substr[i];

                    faceid = scanningService.getFaceID(res, "faceId");

                    left = getValue(res, "left");
                    top = getValue(res, "top");
                    width = getValue(res, "width");
                    height = getValue(res, "height");

                    intarray[4 * i] = left;
                    intarray[4 * i + 1] = top;
                    intarray[4 * i + 2] = width;
                    intarray[4 * i + 3] = height;

                    alias[i] = scanningService.GetMatchAlias(faceid, trainingpath);
                }

                progress = 80f;

                DataSet[] dsarray = userService.GetDataSetsByAlias(alias);
                string[] names = userService.GetDisplayNameByDsarray(dsarray);
                DataSet myds = MergeDataSet(dsarray);
                imageService.DrawImg(filepath, drawfilepath, intarray, names, facenum);

                var allDetectedPeople = userService.GetPersonListByDataSet(myds);
                personlist.Persons = allDetectedPeople.Where(p => p.IsCustomer == false).ToList();
                personlist.Customers = allDetectedPeople.Where(p => p.IsCustomer == true).ToList();
                personlist.ImageURL = "./images/" + drawfilename;
            }

            progress = 100f;

            return PartialView(personlist);
        }

        [HttpGet]
        public ActionResult CustomerDetail(string alias)
        {

            string[] aliasarray = { alias };

            DataSet[] dsarray = userService.GetDataSetsByAlias(aliasarray);
     
            DataSet myds = MergeDataSet(dsarray);
            

            var customerperson = userService.GetPersonListByDataSet(myds);


            var person = customerperson.FirstOrDefault();

            return PartialView("_CustomerDetail", person);
        }

        [HttpPost]
        public ActionResult ScanProgress()
        {
            return Json(string.Format("{0:0.##\\%}", progress));
        }

        public PersonListViewModel fakeViewModel()
        {
            var personListViewModel = new PersonListViewModel();

            var person1 = new Person();
            person1.displayname = "Dwarf One";
            person1.alias = "one";
            person1.title = "Athelete";
            person1.specialty = "Strength";
            person1.team = "Team 1";
            person1.favoritesport = "Weightlifting";
            person1.photoPath = "./Content/Images/test_img_1.png";
            person1.IsCustomer = true;
            person1.Email = "one@contoso.com";
            person1.PersonalExperiences = "Hornored as best DJ in 2015.\n\rGraduate from Master of Computer Science in Stanford University in 2014\n\rPersonal experience of a human being is the moment-to-moment experience and sensory awareness of internal and external events or a sum of experiences forming an empirical unity such as a period of life";
            person1.Comment = "Hornored as best DJ in 2015.\n\rGraduate from Master of Computer Science in Stanford University in 2014\n\rPersonal experience of a human being is the moment-to-moment experience and sensory awareness of internal and external events or a sum of experiences forming an empirical unity such as a period of life";
            var person2 = new Person();
            person2.displayname = "Dwarf Two";
            person2.alias = "two";
            person2.title = "Safeguard";
            person2.specialty = "Clairvoyance";
            person2.team = "Team 2";
            person2.favoritesport = "Hao Change Hao Change Hao Change Hao Change Hao Change Hao Change Hao Change Hao Change Hao Change Hao Change";
            person2.photoPath = "./Content/Images/test_img_2.png";
            person2.Email = "two@contoso.com";
            var person3 = new Person();
            person3.displayname = "Dwarf Three";
            person3.alias = "three";
            person3.title = "Tank";
            person3.specialty = "Impregnable";
            person3.team = "Team 3";
            person3.favoritesport = "";
            person3.photoPath = "./Content/Images/test_img_3.png";
            person3.Email = "three@contoso.com";

            var allDetctedPeople = new List<Person>();
            allDetctedPeople.Add(person1);
            allDetctedPeople.Add(person2);
            allDetctedPeople.Add(person3);

            personListViewModel.Persons = allDetctedPeople.Where(p => p.IsCustomer == false).ToList();
            personListViewModel.Customers = allDetctedPeople.Where(p => p.IsCustomer == true).ToList();

            personListViewModel.ImageURL = "./Content/Images/test.jpg";

            return personListViewModel;
        }

        public DataSet MergeDataSet(DataSet[] dsarray)
        {
            DataSet myds = new DataSet();

            for (int i = 0; i < dsarray.Length; i++)
            {
                myds.Merge(dsarray[i]);
            }

            return myds;
        }

        public int getValue(string str, string scanstr)
        {
            int inputl = scanstr.Length;
            int topindex = str.IndexOf(scanstr);

            char[] carray = str.ToCharArray();

            int i = topindex + inputl + 2;
            int j = 0;
            char[] topca = new char[10];

            while (carray[i] != ',' && carray[i] != '}' && j < 10)
            {
                topca[j] = carray[i];
                j++;
                i++;
            }

            string topstring = new string(topca);

            int topvalue = Convert.ToInt32(topstring);
            return topvalue;
        }
    }
}

PhotoProspector/Views/Scan/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Scripts.Render("~/bundles/scan")
@Scripts.Render("~/bundles/loadgo")
@Styles.Render("~/Content/scan")
@Styles.Render("~/Content/custombutton")

<div id="scan_container">
    <div id="uploaded_preview">
        <div id="preview_img_container">
            <img id="preview_img" src="@ViewBag.fileName" />
        </div>
    </div>
    <div id="uploaded_options">
        <svg class="hidden">
            <defs>
                <clipPath id="clipBox" clipPathUnits="objectBoundingBox">
                    <polygon points="0,0 0,1 0.35,1 0.35,0.6 0.65,0.6 0.65,1 1,1 1,0" />
                </clipPath>
            </defs>
        </svg>
        <div id="scan_progress">0%</div>
        <div id="buttons_container" class="box bg-1">
            <button id="scan_button" class="custom-button custom-button--itzel custom-button--text-thick"><i class="custom-button__icon icon icon-printer"></i><span>Start Scaning</span></button>
            <button id="upload_button" class="custom-button custom-button--itzel custom-button--text-thick"><i class="custom-button__icon icon icon-home"></i><span>Return Home</span></button>
        </div>
    </div>
</div>

PhotoProspector/Views/Scan/Scan.cshtml
@model PhotoProspector.ViewModels.PersonListViewModel

@Styles.Render("~/Content/scanresult")
@Styles.Render("~/Content/custombutton")
@Scripts.Render("~/bundles/scanresult")

<div id="scan_result_preview">
    <div id="preview_img_container">
        <img id="scan_result_img" src="@Model.ImageURL" />
    </div>
</div>
<div id="uploaded_options">
    <svg class="hidden">
        <defs>
            <clipPath id="clipBox" clipPathUnits="objectBoundingBox">
                <polygon points="0,0 0,1 0.35,1 0.35,0.6 0.65,0.6 0.65,1 1,1 1,0" />
            </clipPath>
        </defs>
    </svg>
    <div id="buttons_container" class="box bg-1">
        <button id="upload_button" class="custom-button custom-button--itzel custom-button--text-thick"><i class="custom-button__icon icon icon-home"></i><span>Return Home</span></button>
    </div>
</div>
<div id="person_info_container">
    @{
        var firstPerson = Model.Persons.FirstOrDefault();
        if (firstPerson != null)
        {
            <h2 class="table_header_title">Microsoft Employees</h2>
            <table id="person_info_table" class="info_table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(p => firstPerson.alias)</th>
                        <th>@Html.DisplayNameFor(p => firstPerson.photoPath)</th>
                        <th>@Html.DisplayNameFor(p => firstPerson.displayname)</th>
                        <th>@Html.DisplayNameFor(p => firstPerson.title)</th>
                        <th>@Html.DisplayNameFor(p => firstPerson.specialty)</th>
                        <th>@Html.DisplayNameFor(p => firstPerson.team)</th>
                        <th>@Html.DisplayNameFor(p => firstPerson.favoritesport)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var person in Model.Persons)
                    {
                        <tr>
                            <td class="lalign">@Html.DisplayFor(p => person.alias)</td>
                            <td class="td_photo"><img class="avatar" src="@person.photoPath" /></td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.displayname)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.title)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.specialty)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.team)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.favoritesport)</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
    @{
        var firstCustomer = Model.Customers.FirstOrDefault();
        if (firstCustomer != null)
        {
            <h2 class="table_header_title">Customers</h2>
            <table id="customer_info_table" class="info_table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(p => firstCustomer.displayname)</th>
                        <th>@Html.DisplayNameFor(p => firstCustomer.photoPath)</th>
                        <th>@Html.DisplayNameFor(p => firstCustomer.Email)</th>
                        <th>@Html.DisplayNameFor(p => firstCustomer.favoritesport)</th>
                        <th>@Html.DisplayNameFor(p => firstCustomer.FavoriteFoods)</th>
                        <th>@Html.DisplayNameFor(p => firstCustomer.Interests)</th>
                        <th>@Html.DisplayNameFor(p => firstCustomer.Phone)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var person in Model.Customers)
                    {
                        <tr>
                            <td class="lalign">@Html.DisplayFor(p => person.displayname)</td>
                            <td class="td_photo"><img class="avatar" src="@person.photoPath" /></td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.Email)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.favoritesport)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.FavoriteFoods)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.Interests)</td>
                            <td class="no_wrap">@Html.DisplayFor(p => person.Phone)</td>
                            <td class="no-wrap">@Html.ActionLink("Detail", "CustomerDetail", "Scan", new { alias = person.alias }, new { @class = "modal-link btn btn-success" })</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
</div>
<div id="modal-container" class="modal fade"
     tabindex="-1" role="dialog">
    <div class="modal-content">
    </div>
</div>

PhotoProspector/Views/Scan/_CustomerDetail.cshtml
@model PhotoProspector.Models.Person

@Styles.Render("~/Content/scanresultdetail")
@Scripts.Render("~/bundles/scanresultdetail")

<div class="modal-body">
    <div id="detail_info_header">
        <h2>@Model.displayname</h2>
        <img class="detail_avatar" src="@Model.photoPath" />
    </div>
    <div id="detail_table_container">
        <table class="detail_table">
            <tbody>
                <tr>
                    <td>Email</td>
                    <td>@Html.DisplayFor(p => Model.Email)</td>
                </tr>
                @if (!string.IsNullOrWhiteSpace(Model.title))
                {
                    <tr>
                        <td>Title</td>
                        <td>@Model.title</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.favoritesport))
                {
                    <tr>
                        <td>Favorite Sport</td>
                        <td>@Model.favoritesport</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.FavoriteFoods))
                {
                    <tr>
                        <td>Favorite Food</td>
                        <td>@Model.FavoriteFoods</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.Interests))
                {
                    <tr>
                        <td>Interests</td>
                        <td>@Model.Interests</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.Phone))
                {
                    <tr>
                        <td>Phone</td>
                        <td>@Model.Phone</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.PersonalExperiences))
                {
                    <tr>
                        <td>Personal Experience</td>
                        <td>@Html.DisplayFor(p => Model.PersonalExperiences)</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.WorkedCompanies))
                {
                    <tr>
                        <td>Worked Companies</td>
                        <td>@Html.DisplayFor(p => Model.WorkedCompanies)</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.ParticipatedProjects))
                {
                    <tr>
                        <td>Participated Projects</td>
                        <td>@Html.DisplayFor(p => Model.ParticipatedProjects)</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.CooperatedMSEmployees))
                {
                    <tr>
                        <td>Cooperated Microsoft Employee</td>
                        <td>@Html.DisplayFor(p => Model.CooperatedMSEmployees)</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.Hornors))
                {
                    <tr>
                        <td>Hornors</td>
                        <td>@Html.DisplayFor(p => Model.Hornors)</td>
                    </tr>
                }
                @if (!string.IsNullOrWhiteSpace(Model.Comment))
                {
                    <tr>
                        <td>Comment</td>
                        <td>@Html.DisplayFor(p => Model.Comment)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div id="detail_info_option">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
    </div>
</div>